### ISSUE TITLE
"Error displaying widget: model not found" in notebook launched in Jupyter Lab

### ISSUE THREAD

**Issue by SteveWald** [microsoft/powerbi-jupyter#19]
Greetings-- 

I have had success running the demo code in a jupyter notebook launched via `jupyter notebook`. However, the very same demo code (in the exact same notebook that worked before!) fails when attempting to render the report **when launched within Jupyter Lab**.  In place of rendering the embedded report, the cell instead outputs this generic Jupyter widget-fail message: **"Error displaying widget: model not found"**

I have followed the special installation instructions provided in the README for Jupyter Lab both in existing and brand new conda environments. In the Jupyter Lab UI, the extension shows as being installed and activated. The txt file attached documents a "fresh" conda environment with the package and lab extensions installed and jupyter lab successfully built, but where I'm still seeing the error. I'm working in a relatively new and updated Windows 10 environment.

Love this package! . . . and hope you can help me get it to run in Jupyter Lab. Thank you!

Steve
[pbi_env.txt](https://github.com/microsoft/powerbi-jupyter/files/6705494/pbi_env.txt)

**Comment by gbrault** [comment]
I have the same issue

**Comment by YC-1412** [comment]
Same issue here. Hope it could be solved soon. The package would be really helpful. Thank you!

**Comment by jcpontet** [comment]
+1

**Comment by vitorkol** [comment]
+1

**Comment by bapat-atharva** [comment]
Hi everyone,

After some investigation, we found that this issue is not related to our package, rather the package manager conda.

Here are couple of solutions to resolve it-
1.  Create a new virtual environment with conda
- conda create --name envname
- Install the required libraries (powerbiclient, jupyterlab, ipywidgets, ...)
- Run the jupyterlab

2. Update conda dependencies
- conda uninstall jupyterlab
- conda install -c conda-forge jupyterlab jupyterlab_widgets ipywidgets
- Run the jupyterlab

For either of them, ensure you have these extensions enabled-
![image](https://user-images.githubusercontent.com/60684660/232989959-c40e9da6-1e98-446b-9ead-3d8c046a6085.png)
