### ISSUE TITLE
Failed to load model class 'ReportModel' from module 'powerbi-jupyter-client'

### ISSUE THREAD

**Issue by Diegomon2609** [microsoft/powerbi-jupyter#47]
The issue appears when I am going to render the report

![image](https://github.com/microsoft/powerbi-jupyter/assets/104916580/3679052d-61d2-40f1-a827-ea478fc6ef58)

**Comment by KotanaSai21** [comment]
We were able to repro the issue. After some investigation, we found that this issue is not related to our package, rather the package manager Conda.

We followed the below steps and able to render the report.
1. Updated the Anaconda and Jupyter Lab to the latest versions.
2. Followed the steps but faced the same issue of the JavaScript error.
3. Executed below commands in the Anaconda prompt shell.
```
jupyter lab clean
jupyter labextension install @jupyter-widgets/jupyterlab-manager
pip install powerbiclient
```
Make sure these extensions are added in jupyter lab.
<img width="257" alt="image" src="https://github.com/microsoft/powerbi-jupyter/assets/47911842/90ae6b12-7208-4bbe-944c-36bae44b3590">

4. After these steps, we were able to embed the report in the jupyter lab.

If the issue still exists, try the steps mentioned [here](https://github.com/microsoft/powerbi-jupyter/issues/19#issuecomment-1514219377).
