### ISSUE TITLE
Update_filters

### ISSUE THREAD

**Issue by adama-hawa** [microsoft/powerbi-jupyter#48]
Hello, is it normal that the report display doesn't update when you apply a filter and do an update_filters?

**Comment by KotanaSai21** [comment]
When you apply filters to report using update_filters the report should get updated. We tried applying to the report and it worked fine for us.

Here is the snapshot of code and the output of report where filter is applied.
![image](https://github.com/microsoft/powerbi-jupyter/assets/47911842/950244e2-e536-4928-8c45-5bda256d5c2c)

<img width="796" alt="image" src="https://github.com/microsoft/powerbi-jupyter/assets/47911842/4cd86a7e-e920-4da0-85c6-d466fd0c7eff">

Could you please provide some additional information.

**Comment by adama-hawa** [comment]
In my case, this is how the filter zone looks: 
![filtre](https://github.com/microsoft/powerbi-jupyter/assets/118438558/967f1d09-7598-4dc2-b39d-fb8ae3c242ca)

**Comment by KotanaSai21** [comment]
Can you confirm if this issue is specific to this Jupyter package ? 

In the [Developer Sandbox](https://playground.powerbi.com/en-us/dev-sandbox), " Select your own report"  and then try adding filters there.  Check the below snapshot and update the filter array with your new array.
<img width="588" alt="image" src="https://github.com/microsoft/powerbi-jupyter/assets/47911842/c63dc340-abb8-4b62-b67c-ea904a0cab0b">

If the filters are being applied to the report, then there might be some issue with jupyter package, else you need to check the filters array. Please try this thing and let us know.

**Comment by adama-hawa** [comment]
Hello, 

The problem was caused by a blocking of the filters by the person who did the reporting.

Thanks for your feedback!
