### ISSUE TITLE
LoadReportFailed - Fail to initialize - Could not resolve cluster

### ISSUE THREAD

**Issue by manjukampali1** [microsoft/powerbi-jupyter#52]
Hi , I am trying to Embed PBI report through Service Principal Authentication . but i am getting error as "LoadReportFailed - Fail to initialize - Could not resolve cluster" 

Please assist

**Comment by v-MadhavC** [comment]
In the powerbi-jupyter library, we use the "embed for your organization" scenario, requiring an AAD token instead of an Embed token, which means using a Service Principal is not supported.

You can implement authentication classes to obtain the access token as detailed in the given reference - [Home · microsoft/powerbi-jupyter Wiki (github.com)](https://github.com/microsoft/powerbi-jupyter/wiki#authenticate-to-power-bi-and-acquire-an-access-token). Alternatively, you can create your own logic to acquire a Power BI AAD token and provide it when creating the Report object. For more information, please refer - [Permission tokens needed to embed a Power BI app - Power BI | Microsoft Learn](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embed-tokens?tabs=embed-for-your-organization)
